AWSTemplateFormatVersion: '2010-09-09'
Description: Role to be assumed by CodePipeline service cross account
Parameters:
    S3Bucket:
        Description: S3 Bucket in Pipeline Account, which holds the artifacts built by codebuild
        Type: String
    PipelineAccount:
        Description: AWS AccountNumber for Pipeline
        Type: Number
    CMKARN:
        Description: ARN of the KMS CMK creates in Pipeline account
        Type: String
Resources:
    CFRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: PipelineAcctCodePipelineCloudFormationRole
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          AWS:
                              - !Ref PipelineAccount
                      Action:
                          - sts:AssumeRole
            Path: /
    CFPolicy:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: PipelineAcctCodePipelineCloudFormationPolicy
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Action:
                          - cloudformation:*
                          - s3:*
                          - iam:PassRole
                      Resource: '*'
                    - Effect: Allow
                      Action:
                          - kms:*
                      Resource: !Ref CMKARN
            Roles:
                - !Ref CFRole
    CFDeployerRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: cloudformationdeployer-role
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service:
                              - cloudformation.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Path: /
    CFDeployerPolicy:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: cloudformationdeployer-policy
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Action:
                          '*'
                          # - lambda:AddPermission
                          # - lambda:CreateFunction
                          # - lambda:DeleteFunction
                          # - lambda:InvokeFunction
                          # - lambda:RemovePermission
                          # - lambda:UpdateFunctionCode
                          # - lambda:GetFunctionConfiguration
                          # - lambda:GetFunction
                          # - lambda:UpdateFunctionConfiguration
                          # - lambda:ListTags
                          # - lambda:TagResource
                          # - lambda:UnTagResource
                          # # - events:* # Required for the sample lambda function to work
                          # - iam:CreateRole
                          # - iam:CreatePolicy
                          # - iam:GetRole
                          # - iam:DeleteRole
                          # - iam:PutRolePolicy
                          # - iam:PassRole
                          # - iam:DeleteRolePolicy
                          # - iam:AttachRolePolicy
                          # - cloudformation:*
                          # - iam:DetachRolePolicy
                          # - apigateway:POST # Create API.
                          # - apigateway:GET # Get API info.
                          # - apigateway:PATCH # Update API resources.
                          # - apigateway:DELETE # Delete API incase of rollback.
                      Resource: '*'
                    - Effect: Allow
                      Action:
                          - s3:PutObject
                          - s3:GetBucketPolicy
                          - s3:GetObject
                          - s3:ListBucket
                      Resource:
                          - !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, '/*']]
                          - !Join ['', ['arn:aws:s3:::', !Ref S3Bucket]]
            Roles:
                - !Ref CFDeployerRole
