AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a CMK in KMS and grants access to other accounts
Parameters:
    StagingAccount:
        Description: AWS AccountNumber for test
        Type: Number
    ProdAccount:
        Description: AWS AccountNumber for production
        Type: Number
    ProjectName:
        Description: Name of the Project
        Type: String
        Default: sample-lambda
    CodeBuildCondition:
        Description: Conditionally adds the access required by code build project role
        Type: String
        Default: false
Conditions:
    AddCodeBuildResource: !Equals [!Ref CodeBuildCondition, true]
Resources:
    KMSKey:
        Type: AWS::KMS::Key
        Properties:
            Description: Used by Assumed Roles in Staging/Prod accounts to Encrypt/Decrypt code
            EnableKeyRotation: true
            KeyPolicy:
                Version: '2012-10-17'
                Id: !Ref AWS::StackName
                Statement:
                    - Sid: Allows admin of the key
                      Effect: Allow
                      Principal:
                          AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
                      Action:
                          - 'kms:Create*'
                          - 'kms:Describe*'
                          - 'kms:Enable*'
                          - 'kms:List*'
                          - 'kms:Put*'
                          - 'kms:Update*'
                          - 'kms:Revoke*'
                          - 'kms:Disable*'
                          - 'kms:Get*'
                          - 'kms:Delete*'
                          - 'kms:ScheduleKeyDeletion'
                          - 'kms:CancelKeyDeletion'
                      Resource: '*'
                    - Sid: Allow use of the key for CryptoGraphy Lambda
                      Effect: Allow
                      Principal:
                          AWS:
                              - !Sub arn:aws:iam::${ProdAccount}:root
                              - !Sub arn:aws:iam::${StagingAccount}:root

                              - !If
                                - AddCodeBuildResource
                                - !Sub arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-CodeBuildRole
                                - !Ref AWS::NoValue
                      Action:
                          - kms:Encrypt
                          - kms:Decrypt
                          - kms:ReEncrypt*
                          - kms:GenerateDataKey*
                          - kms:DescribeKey
                      Resource: '*'
    KMSAlias:
        Type: AWS::KMS::Alias
        Properties:
            AliasName: !Sub alias/codepipeline-crossaccounts
            TargetKeyId: !Ref KMSKey
    ArtifactBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain

Outputs:
    CMK:
        Value: !GetAtt [KMSKey, Arn]
    ArtifactBucket:
        Value: !Ref ArtifactBucket
